[package]
name = "HM Bachelor's thesis template"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Stefanie Schmid"]
license = "MIT"
description = "Unofficial Bachelor's thesis template for Munich University of Applied Sciences (Hochschule München)."
repository = "https://github.com/fine-seat/hm-typst-template"
categories = ["thesis"]